<?php
$css = array("divStyle rnOffset30 rnWidth70", "linkStyle", "activeLink", "np");
?>
<div class="container bordered">

    <div class="row">

        <div class="col-md-8 col-md-offset-3">
           
            </br></br>
        </div>


    </div>

    
    <div class="row">
        <div class="col-md-5 col-md-offset-4">
            <?php while ($row = $result->fetch_assoc()): ?>
                <p><?php echo $row['id'] . ") " . $row['number'] . " - " . $row['creation_time']; ?></p>
            <?php endwhile; ?>
        </div>

    </div>

    <div class="row">
        <?php 
        $controller = "users";
        $action = "wyciag";
        $db->createPagination($css, 5, $controller, $action); 
        ?>
    </div>
    
</div>