<?php
if (!isset($_SESSION['user']) || empty($_SESSION['user'])) {
    $hallo = 'Jesteś niezalogowany(a).';
} else {
    $hallo = 'Witaj, ' . htmlentities($_SESSION['user']) . '.';
}
?>

<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>PHPMVCSkeleton</title>

        <script src="src/js/jquery-1.11.1/jquery.min.js"></script>
        <script src="src/js/jquery-ui-1.11.1.custom/jquery-ui.min.js"></script>
        <script src="src/js/jquery-easing-1.3/jquery.easing.min.js"></script>
        <script type="text/javascript" src="src/js/mainScript.js" ></script>
        
        <link rel="stylesheet" type="text/css" href="src/css/bootstrap-3.2.0-dist/js/bootstrap.js" />
        <link rel="stylesheet" type="text/css" href="src/css/bootstrap-3.2.0-dist/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="src/css/mainStyle.css" />
        <link rel="stylesheet" type="text/css" href="src/css/styleCarousel.css" />
        <script type="text/javascript" src="src/js/jquery_functions.js" ></script>

    </head>
    <body>

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="">

                <div class="navbar-header">

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="#">PHPMVCSkeleton</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">

                        <li><img src="src/img/logo.php.gif" width="75" /></li>
                        <li class="active"><a href="<?php echo $this->_url('main', 'index'); ?>">Strona główna</a></li>
                        <li><a href="<?php echo $this->_url('main', 'index'); ?>#informacje">Informacje</a></li>
                        <li><a href="<?php echo $this->_url('main', 'index'); ?>#kontakt">Kontakt</a></li>
                        <?php if (!isset($_SESSION['user'])): ?>
                            <li><a href="<?php echo $this->_url('entry', 'login'); ?>">Logowanie</a></li>
                            <li><a href="<?php echo $this->_url('entry', 'register'); ?>">Rejestracja</a></li>
                        <?php endif; ?>
                        <?php if (isset($_SESSION['user'])): ?>
                            <li><a href="<?php echo $this->_url('entry', 'logout'); ?>">WYLOGUJ</a></li>
                        <?php endif; ?>

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container center-block">

            <div class="row">

                <div id="containerKar">

                    <div id="logo">
                        <img src="src/img/carousel/logo.png" alt="logo" />
                    </div>

                    <div id="haslo">
                        <img src="src/img/carousel/haslo.png" alt="haslo" />
                    </div>

                    <div id="tekst">
                        <img src="src/img/carousel/tekst.png" alt="tekst" />
                    </div>

                    <div id="przycisk">
                        <a href="#"><img src="src/img/carousel/przycisk.png" alt="przycisk" /></a>
                    </div>

                </div>


            </div>

            <div class="row">

                <h3 class="text-justify">
                    <?php echo $hallo; ?>
                </h3>


            </div>

        </div>

        <div class="container center-block">

            <div class="row">
                <?php echo \app\lib\BreadCrumb::createBC(); ?>
            </div>

        </div>

        <div id="notification">
            <div>
                <a id="end" href="#"><h4>X</h4></a>
            </div>
            <div >
                <h4 id="info"></h4>
            </div>
        </div>
