
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <a href="<?php echo $this->_url('cd', 'show'); ?>"><h3>ZOBACZ WSZYSTKIE ZWIERZETA</h3></a> 
    </div>
</div>
<div class="container bordered basicBackground">

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <a href="<?php echo $this->_url('ssaki', 'index'); ?>"><h3>SSAKI</h3></a> 
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <p class="text-left">
                Ssaki (Mammalia) – zwierzęta należące do kręgowców, charakteryzujące się głównie występowaniem 
                gruczołów mlekowych u samic, zazwyczaj obecnością owłosienia (włosy lub futro; silnie zredukowane 
                u gatunków wodnych, jak hipopotamy, u waleni całkowicie zanikają przed porodem lub w trakcie) 
                oraz stałocieplnością (potocznie "ciepłokrwistość"). Większość ssaków utrzymuje temperaturę w 
                granicach 36–39 °C. Stałocieplność umożliwia aktywny tryb życia w różnych 
                środowiskach – od mroźnych obszarów podbiegunowych do gorących tropików. 
                Futro i tłuszcz pomagają uchronić się przed zimnem, a wydzielanie potu i 
                szybki oddech pomagają pozbyć się nadmiernego ciepła.
                Ssaki zamieszkują zarówno środowiska wodne (walenie i syreny), jak i lądowe (większość), 
                opanowały także przestrzeń powietrzną (nietoperze). 
                Obecnie żyje na świecie blisko 5500 gatunków ssaków[2]. 
                Z wyjątkiem nielicznych jajorodnych stekowców, wszystkie współczesne ssaki są żyworodne.
                Zdecydowanie największym rzędem co do liczby gatunków pośród ssaków są gryzonie, 
                obejmujące ponad 2200 gatunków. Następnie nietoperze, z ok. 1100 gatunkami. 
                Najmniejszymi liczebnie grupami ssaków są słoniowate (trzy gatunki) i 
                mrówniki z jednym przedstawicielem. Liczba ssaków jest stosunkowo niewielka w porównaniu z innymi zwierzętami. 
                Największym żywym ssakiem i zarazem największym ssakiem w historii jest płetwal błękitny. 
                Osiąga on ok. 30 m długości i 180 ton wagi. Najmniejszymi ssakami są nietoperze i ryjówki. 
                Nietoperz ryjkonos malutki z południowo-wschodniej Azji waży zaledwie 1,5 g, 
                a rozpiętość jego skrzydeł wynosi 15 cm. Ryjówka etruska waży 2 g, a jej długość łącznie z ogonem to zaledwie 4 cm.

            </p>
        </div>
    </div>


    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <a href="<?php echo $this->_url('ptaki', 'index'); ?>"><h3>PTAKI</h3></a> 
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <p class="text-left">
                Ptaki (Aves) – gromada stałocieplnych zwierząt z podtypu kręgowców. 
                Jest najbardziej zróżnicowaną spośród gromad kręgowców lądowych – 
                istnieje około 10 tys. gatunków ptaków, które zamieszkują ekosystemy na całym świecie. 
                Ich wielkość waha się od 5 cm u koliberka hawańskiego do 2,7 m u strusia.
                Charakterystyczne dla ptaków nowoczesnych (Neornithes) są: skóra wytwarzająca pióra, 
                przednie kończyny przekształcone w skrzydła, szczęki okryte rogowym dziobem, 
                u współczesnych przedstawicieli pozbawionym zębów, lekki, mocny szkielet i czterodziałowe serce. 
                Ptaki są zazwyczaj zdolne do lotu (choć niektóre gatunki są wtórnie nielotne) – 
                ich układ pokarmowy oraz oddechowy są przystosowane do tej zdolności. 
                Poza tym odznaczają się wysoką aktywnością metaboliczną. Rozmnażają się przez składanie i wysiadywanie otoczonych 
                twardą skorupą jaj. Niektóre ptaki, szczególnie krukowate i papugowe należą do najbardziej inteligentnych 
                gatunków zwierząt, zdolnych do tworzenia i używania przyrządów pomocniczych, 
                jak i przekazujących tę wiedzę następnym pokoleniom[1].

                Wiele gatunków odbywa dalekodystansowe wędrówki, inne przemieszczają się mniej regularnie na krótsze odległości. 
                Są zwierzętami społecznymi – porozumiewają się przy pomocy wizualnych sygnałów oraz zawołań kontaktowych, jak i śpiewem, biorą udział we wspólnych lęgach, polowaniach, przepędzaniu drapieżników, zgrupowaniach migracyjnych.

                Większość gatunków ptaków żyje monogamicznie, najczęściej na czas jednego sezonu, czasami na okres kilku lat, 
                rzadziej tworzą tę samą parę przez całe życie. Inne gatunki tworzą lęgowe systemy poligyniczne – 
                z kilkoma samicami przypadającymi na jednego samca. Rzadko spotyka się gatunki poliandryczne z wieloma 
                samcami i jedną samicą. Jaja są zwykle składane do gniazd i wysiadywane przez rodziców. 
                Cechą charakterystyczną dla większości ptaków jest długi okres opiekuńczy nad wyklutymi pisklętami.

                Wiele gatunków ptaków ma znaczenie gospodarcze dla człowieka, najczęściej jako zwierzęta użytkowe. 
                Są przede wszystkim źródłem pożywienia, pozyskiwanego przez hodowlę lub polowania. 
                Zastosowanie gospodarcze znajdują także części pozyskiwane z ptaków np. pióra. 
                Niektóre gatunki, szczególnie ptaki śpiewające, jak i papugowate, są popularnymi zwierzętami domowymi. 
                Poza tym odchody kilku gatunków są używane jako nawóz w rolnictwie. 
                Około 120–130 gatunków ptaków wymarło od XVII w. w rezultacie ludzkiej działalności, 
                setki innych gatunków wymarło wcześniej. Obecnie ocenia się około 1200 gatunków 
                jako zagrożonych wyginięciem przez czynniki antropogeniczne, 
                z drugiej strony człowiek stara się jednak o ich ochronę. 
                Ptaki są także elementem ludzkiej kultury – od religii przez poezję do nauki. 
                Dział biologii badający ptaki to ornitologia. 
                Amatorska obserwacja ptaków rozwinęła się w ostatnich dekadach do 
                rozmiarów masowego hobby w wielu krajach rozwiniętych.

            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <a href="<?php echo $this->_url('gady', 'index'); ?>"><h3>GADY</h3></a> 

        </div>
    </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <p class="text-left">
                Gady (Reptilia, od łac. repto – czołgać się) – parafiletyczna grupa zmiennocieplnych owodniowców. 
                Współczesne gady są pozostałością po znacznie większej grupie zwierząt, 
                której największy rozkwit przypadł na erę mezozoiczną. 
                Obecnie żyją tylko cztery rzędy gadów, ich pozostałe znane linie ewolucyjne wymarły. 
                Niektóre kopalne gady naczelne, czyli archozaury (takie jak pterozaury i dinozaury), 
                były prawdopodobnie zwierzętami stałocieplnymi.

                W tradycyjnej linneuszowskiej klasyfikacji kręgowców gady wyodrębniano jako gromadę, 
                do której zaliczano wszystkie owodniowce z wyjątkiem ptaków i ssaków. Jednak tak definiowana 
                gromada gadów jest parafiletyczna, gdyż należą do niej przodkowie ptaków i ssaków, lecz obie te 
                gromady nie są do niej zaliczane. Prof. Michael J. Benton zaproponował, by tradycyjnie pojmowane 
                "gady" zastąpić dwiema gromadami owodniowców: gromadą zauropsydów (Sauropsida), obejmującą anapsydy 
                i klad Eureptilia, w tym diapsydy (właśnie do tej gromady należą wszystkie współcześnie żyjące "gady"), 
                oraz gromadą synapsydów (Synapsida)[1].

                Niektórzy naukowcy podejmowali też próby przedefiniowania gadów, tak by stały się grupą monofiletyczną. 
                Np. Gauthier, Kluge i Rowe (1988) zdefiniowali Reptilia jako grupę obejmującą ostatniego wspólnego przodka 
                współczesnych żółwi i przedstawicieli kladu Sauria (obejmującego grupy Lepidosauromorpha i Archosauromorpha) 
                oraz wszystkich jego potomków[2]; z kolei Laurin i Reisz (1995) zdefiniowali 
                Reptilia jako klad obejmujący ostatniego wspólnego przodka żółwi i diapsydów oraz wszystkich 
                jego potomków[3]. Nie jest pewne, czy w wypadku przyjęcia którejś z tych definicji gady byłyby synonimem 
                zauropsydów i jakie zwierzęta należałyby do tej grupy (m.in. ze względu na niepewną pozycję filogenetyczną żółwi – 
                tradycyjnie zaliczanych do anapsydów, ale w niektórych nowszych publikacjach uznawanych za diapsydy z kladu Sauria). 
                Modesto i Anderson (2004) zdefiniowali Reptilia jako największy (obejmujący najwięcej gatunków) klad, do 
                którego należą gatunki Lacerta agilis i Crocodylus niloticus, ale do którego nie należy Homo sapiens; tak 
                definiowane gady byłyby synonimem zauropsydów[4]. W wypadku przyjęcia którejś z tych definicji do gadów należałyby
                ptaki, natomiast nie należałyby do nich synapsydy.
            </p>
        </div>
    </div>

    <div class="container">
        
        <div class="row">
            <div class="col-md-11">

                <h3>Informacje</h3>
            </div>

        </div>


        <div class="row">
            <a name='informacje'></a>
            <div class="col-md-11">
                <p class="text-justify">
                    PHPMVCSkeleton jest aplikacją mającą ułatwić szybkie tworzenie aplikacji. Znajac logikę tej aplikacji można
                    w łatwo tworzyć rózne serwisy internetowe. Projekt jest jeszcze na etapie rozwojowym. Napisałem ta aplikację
                    w celu cwiczeń w obiektowym PHP, oraz jako dodatek do mojego portfolio.
                    Na tych stronach jest zaprezentowanych kilka kontrolerów, z założenia głównie prezentacyjnych.
                </p>
            </div>

        </div>


    </div>

    <div class="container">

        <div class="row">
            <div class="col-md-11">
                <a name='kontakt'></a>
                <h3>Kontakt</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-0">
                <p class="text-justify">
                    Piotr Klimaszewski</br>
                    rnestk@interia.pl</br>
                    533 803 000
                </p>
            </div>

        </div>


    </div>

</div>

<!--Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                    Aenean efficitur, tortor vel tristique tristique, orci urna volutpat orci, 
                    commodo gravida nisl urna quis urna. Duis sagittis enim quis sapien elementum, 
                    id lacinia orci porttitor. Duis sit amet sem faucibus, mattis nisi ut, euismod dui. 
                    Aenean id sem a purus aliquet scelerisque. Pellentesque efficitur ultricies eleifend. 
                    Donec risus nunc, porttitor non congue eu, ultricies sed tortor. 
                    Nullam malesuada maximus urna eu tincidunt. 
                    Cras id auctor justo, nec malesuada odio. 
                    In vel iaculis turpis. Praesent eget magna eu quam hendrerit tincidunt ut eget diam. 
                    Sed velit augue, scelerisque eu metus eu, tincidunt mattis mauris. Nullam in velit iaculis, 
                    elementum nisi quis, dictum neque. In nec quam in turpis vulputate rhoncus. 
                    Phasellus sagittis elit in tellus tristique, non imperdiet nulla convallis. 
                    Quisque ut sapien nibh. Nulla varius facilisis libero, vitae commodo lectus pellentesque sodales. -->