
<div class="container">
    
    <div class="error">
        <div class="errorImg">
            <img src="src/img/error.png" width="300"/>
        </div>
        <div class="errorDetails">
            <h2>Wystąpił błąd.</h2>
            <h3>Szczegóły:</h3>
            <div>
                <p>
                    <?php echo '<b>Treść błędu:</b> ' . $error->getMessage() . '</br>'; ?>
                    <?php echo '<b>Plik:</b> ' . $error->getFile() . '</br>'; ?>
                    <?php echo '<b>Linia:</b> ' . $error->getLine() . '</br>'; ?>
                    <?php echo '<b>Sczegóły:</b></br>'; ?>
                    <?php print_r($error->getTrace()); ?>
                </p>
                
            </div>
        </div>
    </div>
    
</div>